# Generated by Django 4.2.2 on 2023-06-17 00:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='content',
            new_name='message',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='title',
            new_name='subject',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
